SELECT RMC001_RANCHO, 
       RMC001_TIPODOCOP, 
       RMC001_ORDEM, 
       RMC001_PRODUTO, 
       RMC001_QTDESOL, 
       RMC001_QTDEATE, 
       RMC001_QTDECAN,
       RMC001_CODSITUACAO,
       RMC001_SITUACAO, 
       RMC001_TRANSFERIDA, 
       RMC001_AXORIGEM, 
       RMC001_AXDESTINO,
       RMTBC001.DATE_CREATED AS DATA

FROM RMTBC001

--FILTROS
WHERE RMC001_TIPODOCOP = 'OP'
  AND RMC001_TRANSFERIDA = :SITUACAO --MANTER FILTRO PARA TRASNFERIDO, NÃO TRASFERIDO E AMBOS
ORDER BY RMTBC001.DATE_CREATED DESC 

--VISUALIZAR OQUE SE ENCONTRA EM ABERTO(2) E TRASNFERIDO (SITUACAO USAR FILTROS DA RMC001 TRASNFERIDA)
--ALMOX 1,13,43,44 ORIGEM
--ALMOX 17 E 18 DESTINO



