SELECT ESA219_PRODUTO AS PRODUTO,
       MAX(ESA219_ETIQUETA) AS LOTE,
       ESA219_QTDETRANSF AS QTD_TRASNFERIDA,
       ESA219_ALMOXORI AS AX_ORIGEM,
       ESA219_ALMOXDES AS AX_DESTINO,
       ESA219_NROLCTOENT AS LCTO_ENTRADA,
       ESA219_NROLCTOSAI AS LCTO_SAIDA,
       ESTBA219.DATE_CREATED AS DATA

FROM ESTBA001, ESTBA219 /*Tabela de produtos e tabela de lançamentos*/

/*MERGE ESATTBA219 COM ESTBA001*/
WHERE ESA219_GRUPO = ESA001_GRUPO
  AND ESA219_EMPRESA = ESA001_EMPRESA
  AND ESA219_FILIAL = 0
  AND ESA219_ALMOXORI = 1
  AND ESA219_ALMOXDES = 14
  
--FILTROS
  AND ESA219_PRODUTO = :PROD /*SELECIONA O PRODUTO AO QUAL QUER CONFERIR*/
  AND ESTBA219.DATE_CREATED BETWEEN :DATAINI AND :DATAFIM /*SELECIONA A DATA DESEJADA*/

--AGRUPADOR PARA A FUNCTION 'MAX'
  GROUP BY ESA219_PRODUTO,
           ESA219_QTDETRANSF,
           ESA219_ALMOXORI,
           ESA219_ALMOXDES,
           ESA219_NROLCTOENT,
           ESA219_NROLCTOSAI,
           ESTBA219.DATE_CREATED
           
  ORDER BY DATA ASC