SELECT COMPONENTE_PRODUTOPAI AS PRODUTO_PAI,
       COMPONENTE_PRODUTO AS PRODUTO,
       COMPONENTE_DESCRICAO AS DESCRIÇÃO,
       COMPONENTE_QUANTIDADE AS QTDE,
       COMPONENTE_DESCRPRODCONF AS PROD_CONF,
       COMPONENTE_ORDEM AS ORDEM,
       COMPONENTE_SEQCOMP AS SEQCOMP,
       COMPONENTE_NIVEL AS NÍVEL,   
       COMPONENTE_RESTRITO AS RESTRITO, 
       COMPONENTE_DTVALINI AS VALIDADE_INI, 
       COMPONENTE_DTVALFIM AS VALIDADE_FIM, 
       COMPONENTE_FANTASMA AS FANTASMA, 
       COMPONENTE_UM AS UNIDADE 

FROM (SELECT NIVEL AS COMPONENTE_NIVEL,
             ECB001_COMPONENTE AS COMPONENTE_PRODUTO,
             ECB001_PRODUTO AS COMPONENTE_PRODUTOPAI,
             ECB001_QTDE AS COMPONENTE_QUANTIDADE,
             ECB001_GRUPO AS COMPONENTE_GRUPO,
             ECB001_EMPRESA AS COMPONENTE_EMPRESA,
             ECB001_RESTRITO AS COMPONENTE_RESTRITO,
             ECB001_ORDEM AS COMPONENTE_ORDEM,
             ECB001_DTVALINI AS COMPONENTE_DTVALINI,
             ECB001_DTVALFIM AS COMPONENTE_DTVALFIM,
             ECB001_PERDA AS COMPONENTE_PERDA,
             ECB001_FANTASMA AS COMPONENTE_FANTASMA,
             ECB001_TIPODEMANDA AS COMPONENTE_TIPODEMANDA,
             ECB001_UM AS COMPONENTE_UM,
             ECFBA001(ECB001_GRUPO, ECB001_EMPRESA, ECB001_PRODUTO, ECB001_SEQCOMP, 'ESA001_DESCRICAO') AS COMPONENTE_DESCRICAO,
             CQFBA003(ECB001_GRUPO, ECB001_EMPRESA, ECB001_COMPONENTE, ECPGA001.ECFPA001004(NIVEL, '', '', 0, 2, 2)) AS COMPONENTE_DESCRPRODCONF,
             ECB001_SEQCOMP AS COMPONENTE_SEQCOMP

        FROM (SELECT LEVEL AS NIVEL,
                     ECB001_RESTRITO,
                     ECB001_GRUPO,
                     ECB001_EMPRESA,
                     ECB001_COMPONENTE,
                     ECB001_DTVALINI,
                     ECB001_DTVALFIM,
                     ECB001_PRODUTO,
                     ECB001_QTDE,
                     ECB001_LOTE,
                     ECB001_FORMULA,
                     ECB001_PERDA,
                     ECB001_FANTASMA,
                     ECB001_TIPODEMANDA,
                     ECB001_UM,
                     ECB001_SEQCOMP,
                     ECPGA001.ECFPA001004(LEVEL, TO_CHAR(ECB001_ORDEM, '00000') || TO_CHAR(ECB001_SEQCOMP, '00000'), '0') AS ECB001_ORDEM

                FROM ECTBB001

               WHERE ECB001_DTVALINI <= SYSDATE  -- TROCADO A LÓGICA DE DATA ORIGINAL
                 AND ECB001_DTVALFIM >= SYSDATE
                 --AND LEVEL <= :NIVEL_MAX

          START WITH ECB001_PRODUTO IN (SELECT DISTINCT ESA001_PRODUTO 
                                        FROM ESTBA001 
                                        WHERE ESA001_GRUPO = ECB001_GRUPO 
                                          AND ESA001_EMPRESA = ECB001_EMPRESA)
                 AND ECB001_DTVALINI <= SYSDATE  
                 AND ECB001_DTVALFIM >= SYSDATE  

    CONNECT BY PRIOR ECB001_COMPONENTE = ECB001_PRODUTO
                 AND ECB001_DTVALINI <= SYSDATE  
                 AND ECB001_DTVALFIM >= SYSDATE  

            ORDER BY ECB001_PRODUTO, ECB001_ORDEM, ECB001_SEQCOMP ASC))

WHERE --COMPONENTE_NIVEL <= :NIVEL_MAX /*REMOVER FILTRO PARA TRAZER QUALQUER COMPONENTE DE QUALQUER NÍVEL INDEPENDENTE*/
  --AND COMPONENTE_PRODUTOPAI = :PRODUTOPAI /*REMOVER FILTRO PARA GERAR TODOS OS PRODUTOS*/
  (COMPONENTE_DESCRICAO IS NULL OR COMPONENTE_DESCRICAO NOT LIKE '%***%')

ORDER BY PRODUTO_PAI