SELECT 
    RECURSO,
    PRODUTO,
    RANCHO,
    SITUACAO,
    SUBSTR(EFFECTIVE.STRING_AGG(FUNCIONADROGA), 1, 3900) AS OP_DATASIMUL
FROM (
    SELECT DISTINCT 
        OPS012_RECURSO AS RECURSO,
        RMB001_PRODUTO || '-' || RMB001_PRODUTOCONF AS PRODUTO,
        RMC001_RANCHO AS RANCHO,
        CASE 
            WHEN RMC001_QTDETRANSF = 0 THEN 'N'
            WHEN RMC001_QTDETRANSF <> 0 THEN 'S'
            ELSE 'INDEFINIDO'
        END AS SITUACAO,
        OPS012_TIPODOC || '-' || OPS012_ORDEM || ' ' || TO_CHAR(OPS012_DATASIMUL, 'DD/MM/YYYY') AS FUNCIONADROGA
    FROM RMTBC001
    INNER JOIN RMTBB001 ON RMC001_GRUPO = RMB001_GRUPO
                       AND RMC001_EMPRESA = RMB001_EMPRESA
                       AND RMC001_FILIAL = RMB001_FILIAL
                       AND RMC001_TIPODOC = RMB001_TIPODOC
                       AND RMC001_RANCHO = RMB001_RANCHO
                       AND RMC001_SOLICITACAO = RMB001_SOLICITACAO
                       AND RMC001_TIPODOCOP = RMB001_TIPODOCOP
    INNER JOIN RMTBE001 ON RMC001_GRUPO = RME001_GRUPO
                       AND RMC001_EMPRESA = RME001_EMPRESA
                       AND RMC001_FILIAL = RME001_FILIAL
                       AND RMC001_TIPODOC = RME001_TIPODOC
                       AND RMC001_RANCHO = RME001_RANCHO
                       AND RMC001_SOLICITACAO = RME001_SOLICITACAO
                       AND RMC001_SEQDEM = RME001_SEQDEM
    JOIN OPTBS012 ON RMB001_PRODUTO = OPS012_PRODUTO
                 AND RMB001_PRODUTOCONF = OPS012_PRODUTOCONF
    WHERE RMC001_ORDEM = OPS012_ORDEM
      AND OPS012_DATASIMUL BETWEEN TO_DATE(:DATA_INICIO, 'DD/MM/YYYY') AND TO_DATE(:DATA_FIM, 'DD/MM/YYYY')
      AND (:TRANSFERIDO = '%' OR (:TRANSFERIDO = 'S' AND RMC001_QTDETRANSF <> 0)
       OR (:TRANSFERIDO = 'N' AND RMC001_QTDETRANSF = 0)))

GROUP BY 
    RECURSO,
    PRODUTO,
    RANCHO,
    SITUACAO;